### ISSUE TITLE
Is there any image to easy install Fledge and run it in docker?

### ISSUE THREAD

**Issue by raissonsouto** [fledge-iot/fledge#1076]
I've only find this `soumyaks/fledge-1.9.2:latest` repo but I don't know if I can rely on it.

Having oficial images on Dockerhub would be amazing.

**Comment by MarkRiddoch** [comment]
We will shortly be creating a new release of Fledge and tis will have a docker image available for it.

**Comment by raissonsouto** [comment]
Hi folks, I trust you're doing well. I wanted to inform you that the project I was part of has been discontinued due to recent work changes. With my shift in roles and the alterations, the use of Fledge is no longer required. Thank you for keeping me in mind, though!
