### ISSUE TITLE
Modbus-C south plugin: option to disable read optimisation

### ISSUE THREAD

**Issue by ReneWassinkAlliander** [fledge-iot/fledge#1110]
The read actions of the Modbus-C south plugin are optimised with the goal to minimize the amount of needed transactions. However: not all hardware devices support this behaviour. It would be useful to have the option to disable the read optimisation.

**Comment by MarkRiddoch** [comment]
A new option has been added that lets the user control the way reads are done. Three options are available, the current block reads, reading individual objects or reading individual registers. This work is currently available on the branch FOGL-7981 but will shortly be merged to develop.

**Comment by MarkRiddoch** [comment]
A fix for this issue is in release 2.2.0
