### ISSUE TITLE
Modbus-TCP south plugin: determine future

### ISSUE THREAD

**Issue by ReneWassinkAlliander** [fledge-iot/fledge#1112]
What is the future goal of the Modbus-TCP plugin? The behaviour (including configuration) is different from the Modbus-C plugin, is missing functionality & documentation. Either add the Modbus-TCP module to the documentation, or delete the repo.

**Comment by Sander3003** [comment]
Fix: Make clear in the readme.md that this is just a example repository.

https://github.com/fledge-iot/fledge-south-modbustcp

**Comment by MarkRiddoch** [comment]
Develop branch is updated
