### ISSUE TITLE
Fledge service does not detect when plugin_shutdown() hangs forever

### ISSUE THREAD

**Issue by FlorentP42** [fledge-iot/fledge#1178]
**Describe the bug**
When a service shutdown is requested, Fledge will call `plugin_shutdown()` on the plugin responsible for this service. If that function never returns (eg: due to some thread join hanging forever in the object destruction), Fledge will not detect it and display logs indicating that the service was stopped successfully, when it clearly was not:
```
Fledge[141] INFO: utils: fledge.services.common.utils: Shutting down the Southbound service 
Fledge hnzsouth_s1[35373]: INFO: South service shutdown in progress.
Fledge[141] INFO: utils: fledge.services.common.utils: Service hnzsouth_s1, id 8c8e4fdf-41f5-44d7-b985-09bb2f5c202e at url http://localhost:43299/fledge/service/shutdown successfully shutdown
```

**To Reproduce**
1. Start Fledge with a south plugin that prints a log periodically and containing an erroneous plugin_shutdown() function that never returns.
2. Create a south service from that plugin and enable it (check Enable in the GUI).
3. Stop that south service (uncheck Enable in the GUI).
4. Notice the 3 log messages above.
5. Notice that the logs from the plugin are still being produced, meaning it is, in fact, not stopped.

**Expected behavior**
When the main plugin of a service hangs during the shutdown process, it is detected by Fledge and after a timeout period:
1. An error log is produced so the user knows there is an issue.
2. The plugin is forcefully stopped (if possible).

**Additional context**
This was encountered and tested on a south service, but it may also affect other types of services.

**Comment by MarkRiddoch** [comment]
The plugin API is specified such that these calls should never hang. It should be considered as a bug in the plugin if any of these calls hang.
