### ISSUE TITLE
Reading values sometimes ending up in the wrong asset

### ISSUE THREAD

**Issue by aklira** [fledge-iot/fledge#1219]
We have observed that during the first run of a new Fledge installation (with Fledge 2.2, doesn't occur with Fledge 2.1) the IEC 104 north and south plugins (available on FledgePower github repo) cannot communicate correctly.
 
The south plugin is supposed to send a special status Reading for a configurable asset. When we had a closer look at the problem we have seen that the Reading values sometimes ended up in another asset and this way our north plugin didn’t see them.
 
Before we call the ingest callback in the south plugin the Reading and asset names always look correct. But in the web interface we can see that some of the Readings end up in the wrong asset.
 
The strange thing is that after a restart of fledge (or better the docker container containing fledge) it seems to work without problems.

We think that it is not related to the asset tracker because the data that we receive in the north plugin seems to be identical with the data shown in the web UI.

**Comment by MarkRiddoch** [comment]
FOGL-8261 opened to track this internally

**Comment by MarkRiddoch** [comment]
The fix for this is now in the develop branch.

**Comment by MarkRiddoch** [comment]
@aklira Can we now close this issue or are you still seeing problems with the latest version?

**Comment by aklira** [comment]
The latest tests I conducted seem to indicate that the bug has disappeared, so yes, we can close the issue.
