### ISSUE TITLE
Running Fledge in Raspberry Pi

### ISSUE THREAD

**Issue by Dibyajyoti-08** [fledge-iot/fledge#1464]
**Title:** Installation Error: Missing `python-dev` and External Management Issue

**Description:**

I followed the installation steps for the project, but encountered errors during the process. Here are the steps I executed and the corresponding errors:

1. I ran the command:
   ```bash
   sudo ./requirements.sh
   ```
   This resulted in the following error:
   ```
   Package python-dev is not available, but is referred to by another package.
   This may mean that the package is missing, has been obsoleted, or is only available from another source.
   However, the following packages replace it:
     python-dev-is-python3

   E: Package 'python-dev' has no installation candidate
   ```

   I noted that `python-dev-is-python3` is available, so I proceeded.

2. Next, I executed:
   ```bash
   make
   ```
   This gave me the following error:
   ```
   cd python ; python3 setup.py build -b ../python_build_dir ; cd /root/git/fledge/ ; cp python/requirements.txt python_build_dir/lib/.
   running build
   running build_py
   cp -r python_build_dir/lib/* /usr/local/fledge/python
   python3 -m pip install -Ir python/requirements.txt --no-cache-dir
   error: externally-managed-environment

   × This environment is externally managed
   ╰─> To install Python packages system-wide, try apt install python3-xyz, where xyz is the package you are trying to install.

   If you wish to install a non-Debian-packaged Python package, create a virtual environment using python3 -m venv path/to/venv.
   Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make sure you have python3-full installed.

   For more information visit http://rptl.io/venv

   note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
   hint: See PEP 668 for the detailed specification.
   make: *** [Makefile:327: python_requirements] Error 1
   ```

### Expected Behavior
I expected the installation to proceed without these errors.

### Environment
- OS: Debian
- Python Version: Python 3.11.2
### Suggested Actions
Could you please provide guidance on resolving these issues? Specifically, I’d appreciate advice on how to handle the missing `python-dev` package and the external management error during the installation process.

Thank you!

**Comment by praveen-garg** [comment]
https://github.com/fledge-iot/fledge/issues/1214#issuecomment-2325517625 may help

**Comment by Dibyajyoti-08** [comment]
Thanks for the help.
