### ISSUE TITLE
Notification service creation did not work. Throws errors in the log.

### ISSUE THREAD

**Issue by sudhirkshirsagar** [fledge-iot/fledge#183]
It was the first time that I created a notification service instance in a working Fledge on Ubuntu 18.04 on i5 machine with 4GB ram.
The log shows:
Oct 8 12:38:24 sudhir-Aspire-5749 Fledge notiserv1[18559]: ERROR: Can not access plugin directory /usr/local/fledge/python/fledge/plugins/notificationDelivery/: No such file or directory

Oct 8 12:38:24 sudhir-Aspire-5749 Fledge notiserv1[18559]: ERROR: Can not access plugin directory /usr/local/fledge/plugins/notificationDelivery/: No such file or directory

Oct 8 12:38:24 sudhir-Aspire-5749 Fledge notiserv1[18559]: ERROR: Can not access plugin directory /usr/local/fledge/python/fledge/plugins/notificationRule/: No such file or directory

Oct 8 12:38:24 sudhir-Aspire-5749 Fledge notiserv1[18559]: ERROR: Can not access plugin directory /usr/local/fledge/plugins/notificationRule/: No such file or directory

**Comment by ashish-jabble** [comment]
@MarkRiddoch We have already a FOGL-3212 JIRA ticket to handle. (backlog)

**Comment by sudhirkshirsagar** [comment]
After the error, I tried to create notification services. They get enabled but don't work.

**Comment by MarkRiddoch** [comment]
Fixes for this are now in the develop branch and should be release in the next few weeks as part of the Fledge 1.9 release.

**Comment by MarkRiddoch** [comment]
1.9 is now released with these fixes.
