### ISSUE TITLE
paths are incorrect on a page Testing Fledge  #fogbench: a Brief Intro 

### ISSUE THREAD

**Issue by joyshmitz** [fledge-iot/fledge#373]
by the [address](https://fledge-iot.readthedocs.io/en/v1.9.0/building_fledge/06_testing.html#fogbench-a-brief-intro)
...
$ sudo cp -r python /usr/local/fledge/python/fledge/plugins/south/
$ sudo pip3 install -r /usr/local/fledge/python/requirements-coap.txt 
# based on the copy command, the python directory with the desired file is copied further along the path
...

**Comment by ashish-jabble** [comment]
Hi @joyshmitz It has been fixed in v1.9.1 release. Please check latest readthdocs https://fledge-iot.readthedocs.io/en/latest/building_fledge/06_testing.html#fogbench-a-brief-intro
