### ISSUE TITLE
Incorrect documentation for north shutdown API

### ISSUE THREAD

**Issue by jchabod** [fledge-iot/fledge#790]
In the page https://fledge-iot.readthedocs.io/en/develop/plugin_developers_guide/04_north_plugins.html#c-c-plugins , there is a probable mistyping in example for `plugin_shutdown` (in C/C++ part)

`uint32_t plugin_shutdown(PLUGIN_HANDLE handle)`
probably should be 
`void plugin_shutdown(PLUGIN_HANDLE handle)`

**Comment by MarkRiddoch** [comment]
Thanks - I will get that updated.

**Comment by MarkRiddoch** [comment]
Fixed in develop branch
