### ISSUE TITLE
get_plugin_info tool SIGSEGV on bad arguments

### ISSUE THREAD

**Issue by jchabod** [fledge-iot/fledge#798]
In file `C/plugins/utils/get_plugin_info.cpp`, The application will SIGSEGV in ARGC=2,

Replace 
```
  if (argc<2)
```

by 
```
  if (argc<3)
```

**Comment by MarkRiddoch** [comment]
Thanks for raising this. I will get this seen fixed.

**Comment by jchabod** [comment]
Note:
As the prgram only work for "plugin_init" function, Isn't ist better to remove second argument and make it hard-coded?

Anyway,  this clearly is a very minor fix... 


Regards.

**Comment by MarkRiddoch** [comment]
A fix for this is now in the develop branch. Also the function has been made an optional argument. This will be released in the next patch release, 2.0.1.

**Comment by ashish-jabble** [comment]
Fixed in PR-https://github.com/fledge-iot/fledge/pull/833 and available onwards v2.0.1
