### ISSUE TITLE
North plugin dispatcher encodes invalid json

### ISSUE THREAD

**Issue by jchabod** [fledge-iot/fledge#830]
In file `north.cpp`, the 2 functions `NorthService::operation` fill invalid JSON content:
- first `{` is not closed
- additionnal double quote enclosing parameter loop. (maybe the sub-quotes need to be doubly-escaped?)

**Comment by MarkRiddoch** [comment]
Thanks for bringing this to our attention. I fix will be added to the develop branch shortly.

**Comment by MarkRiddoch** [comment]
A fix for this issue is now in the develop branch and will be released in the next patch release, 2.0.1.

**Comment by ashish-jabble** [comment]
Fixed via PR-https://github.com/fledge-iot/fledge/pull/832 and available onwards v2.0.1
